### ISSUE TITLE
Querying double numbers only return 4 significant digits...

### ISSUE THREAD

**Issue by Robert-M-Muench** [dlang-community/d2sqlite3#63]
I'm querying a value which is stored like this in SQLite `82.5850709125308` but get back `82.5851``

How can I get back the full precision?

**Comment by biozic** [comment]
How did you check the value you got back from the database? `82.5851` is what `writeln` would print but not what the actual value is.

See:
```d
unittest {
    auto db = Database(":memory:");
    db.run("CREATE TABLE test (val FLOAT)");
    db.run("INSERT INTO test (val) VALUES (82.5850709125308)");
    auto value = db.execute("SELECT val FROM test").oneValue!double;
    assert(value == 82.5850709125308);
}
```

**Comment by Robert-M-Muench** [comment]
Ups, sorry. Didn't know that writeln doesn't spit out maximum precision by default. Things work.
